# Generated by Django 5.1.5 on 2025-01-17 18:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Check'), ('repair', 'Repair'), ('overhaul', 'Overhaul'), ('inspection', 'Inspection')], max_length=20)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(seconds=14400))),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('technician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='aircraft_data.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('fuel_efficiency', 'Fuel Efficiency'), ('flight_time', 'Flight Time'), ('delays', 'Delays'), ('maintenance_cost', 'Maintenance Cost')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='aircraft_data.aircraft')),
            ],
        ),
    ]
