# Generated by Django 4.2.17 on 2025-02-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'managed': False},
        ),
    ]
